hexlify() takes bytes, not str
```
ERROR: Test the to dictionary method of a tick
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/workspace/test_tribler_python3/tribler/Tribler/Test/Community/Market/test_tick.py", line 81, in test_to_dictionary
    "block_hash": hexlify('0' * 32)
TypeError: a bytes-like object is required, not 'str'
```